input_symbols = {
    "mixed_symbols": [
        {"symbol": "AAPL", "api": "swyftx"},
        {"symbol": "AXS", "api": "swyftx"},
        {"symbol": "TSLA", "api": "swyftx"},
        {"symbol": "FB", "api": "swyftx"},
        {"symbol": "GOOG", "api": "swyftx"},
        {"symbol": "MSFT", "api": "swyftx"},
        {"symbol": "NVDA", "api": "swyftx"},
        {"symbol": "NVAX", "api": "swyftx"},
        {"symbol": "BUD", "api": "swyftx"},
        {"symbol": "AMZN", "api": "swyftx"},
        {"symbol": "INFY", "api": "swyftx"},
        {"symbol": "RTX", "api": "swyftx"},
        # {"symbol": "ADA-USD", "api": "swyftx"},
        {"symbol": "ETH-USD", "api": "swyftx"},
        {"symbol": "SOL-USD", "api": "swyftx"},
        # {"symbol": "XRP-USD", "api": "swyftx"},
        {"symbol": "DOGE-USD", "api": "swyftx"},
        {"symbol": "SHIB-USD", "api": "swyftx"},
        {"symbol": "MATIC-USD", "api": "swyftx"},
        # {"symbol": "ATOM-USD", "api": "swyftx"},
        # {"symbol": "FTT-USD", "api": "swyftx"},
        # {"symbol": "BNB-USD", "api": "swyftx"},
        {"symbol": "WBTC-USD", "api": "swyftx"},
        {"symbol": "TRX-USD", "api": "swyftx"},
        {"symbol": "BAT-USD", "api": "swyftx"},
        {"symbol": "PAXG-USD", "api": "swyftx"},
    ],
    "nyse_symbols_big": [
        {"symbol": "C", "api": "swyftx"},
        {"symbol": "PFE", "api": "swyftx"},
        {"symbol": "GE", "api": "swyftx"},
        {"symbol": "AIG", "api": "swyftx"},
        {"symbol": "WMT", "api": "swyftx"},
        {"symbol": "IBM", "api": "swyftx"},
        {"symbol": "BAC", "api": "swyftx"},
        {"symbol": "JNJ", "api": "swyftx"},
        {"symbol": "GS", "api": "swyftx"},
        {"symbol": "CVX", "api": "swyftx"},
        {"symbol": "PG", "api": "swyftx"},
        {"symbol": "MO", "api": "swyftx"},
        {"symbol": "JPM", "api": "swyftx"},
        {"symbol": "COP", "api": "swyftx"},
        {"symbol": "VLO", "api": "swyftx"},
        {"symbol": "TXN", "api": "swyftx"},
        {"symbol": "SLB", "api": "swyftx"},
        {"symbol": "HD", "api": "swyftx"},
        {"symbol": "UNH", "api": "swyftx"},
        {"symbol": "MRK", "api": "swyftx"},
        {"symbol": "VZ", "api": "swyftx"},
        {"symbol": "CAT", "api": "swyftx"},
        {"symbol": "PD", "api": "swyftx"},
        {"symbol": "DNA", "api": "swyftx"},
        {"symbol": "GM", "api": "swyftx"},
        {"symbol": "HPQ", "api": "swyftx"},
        {"symbol": "KO", "api": "swyftx"},
        {"symbol": "AXP", "api": "swyftx"},
        {"symbol": "UPS", "api": "swyftx"},
        {"symbol": "MMM", "api": "swyftx"},
        {"symbol": "VIA", "api": "swyftx"},
        {"symbol": "WFC", "api": "swyftx"},
        {"symbol": "HAL", "api": "swyftx"},
        {"symbol": "BA", "api": "swyftx"},
        {"symbol": "F", "api": "swyftx"},
        {"symbol": "X", "api": "swyftx"},
        {"symbol": "LLY", "api": "swyftx"},
        {"symbol": "RIG", "api": "swyftx"},
        {"symbol": "AAPL", "api": "swyftx"},
        {"symbol": "AXS", "api": "swyftx"},
        {"symbol": "TSLA", "api": "swyftx"},
        {"symbol": "FB", "api": "swyftx"},
        {"symbol": "GOOG", "api": "swyftx"},
        {"symbol": "MSFT", "api": "swyftx"},
        {"symbol": "NVDA", "api": "swyftx"},
        {"symbol": "NVAX", "api": "swyftx"},
        {"symbol": "BUD", "api": "swyftx"},
        {"symbol": "AMZN", "api": "swyftx"},
        {"symbol": "INFY", "api": "swyftx"},
        {"symbol": "RTX", "api": "swyftx"},
        {"symbol": "GME", "api": "swyftx"},
    ],
    "nyse_symbols_medium": [
        {"symbol": "C", "api": "swyftx"},
        {"symbol": "PFE", "api": "swyftx"},
        {"symbol": "GE", "api": "swyftx"},
        {"symbol": "AIG", "api": "swyftx"},
        {"symbol": "WMT", "api": "swyftx"},
        {"symbol": "IBM", "api": "swyftx"},
        {"symbol": "BAC", "api": "swyftx"},
        {"symbol": "JNJ", "api": "swyftx"},
        {"symbol": "GS", "api": "swyftx"},
        {"symbol": "CVX", "api": "swyftx"},
        {"symbol": "PG", "api": "swyftx"},
        {"symbol": "MO", "api": "swyftx"},
        {"symbol": "JPM", "api": "swyftx"},
        {"symbol": "COP", "api": "swyftx"},
        {"symbol": "VLO", "api": "swyftx"},
        {"symbol": "TXN", "api": "swyftx"},
        {"symbol": "GME", "api": "swyftx"},
    ],
    "nyse_symbols": [
        {"symbol": "MSFT", "api": "swyftx"},
        {"symbol": "C", "api": "swyftx"},
    ],
    "mixed_symbols_small": [
        {"symbol": "C", "api": "swyftx"},
        {"symbol": "SOL-USD", "api": "swyftx"},
    ],
    "crypto_symbol": [
        {"symbol": "SHIB-USD", "api": "swyftx"},
    ],
    "crypto_symbols_all": [
        # {"symbol": "ADA-USD", "api": "swyftx"},
        {"symbol": "SHIB-USD", "api": "swyftx"},
        {"symbol": "ETH-USD", "api": "swyftx"},
        {"symbol": "SOL-USD", "api": "swyftx"},
        # {"symbol": "XRP-USD", "api": "swyftx"},
        {"symbol": "DOGE-USD", "api": "swyftx"},
        {"symbol": "MATIC-USD", "api": "swyftx"},
        # {"symbol": "ATOM-USD", "api": "swyftx"},
        # {"symbol": "FTT-USD", "api": "swyftx"},
        # {"symbol": "BNB-USD", "api": "swyftx"},
        {"symbol": "WBTC-USD", "api": "swyftx"},
        {"symbol": "TRX-USD", "api": "swyftx"},
        {"symbol": "BAT-USD", "api": "swyftx"},
        {"symbol": "PAXG-USD", "api": "swyftx"},
        {"symbol": "AAVE-USD", "api": "swyftx"},
        {"symbol": "AVAX-USD", "api": "swyftx"},
        {"symbol": "BCH-USD", "api": "swyftx"},
        {"symbol": "LINK-USD", "api": "swyftx"},
        {"symbol": "DAI-USD", "api": "swyftx"},
        #{"symbol": "GRT-USD", "api": "swyftx"},
        {"symbol": "LTC-USD", "api": "swyftx"},
        {"symbol": "MKR-USD", "api": "swyftx"},
        {"symbol": "SUSHI-USD", "api": "swyftx"},
        {"symbol": "YFI-USD", "api": "swyftx"},
    ],
    "crypto_symbols_cheap": [
        # {"symbol": "ADA-USD", "api": "swyftx"},
        {"symbol": "SHIB-USD", "api": "swyftx"},
        # {"symbol": "ETH-USD", "api": "swyftx"},
        # {"symbol": "SOL-USD", "api": "swyftx"},
        # {"symbol": "XRP-USD", "api": "swyftx"},
        {"symbol": "DOGE-USD", "api": "swyftx"},
        {"symbol": "MATIC-USD", "api": "swyftx"},
        # {"symbol": "ATOM-USD", "api": "swyftx"},
        # {"symbol": "FTT-USD", "api": "swyftx"},
        # {"symbol": "BNB-USD", "api": "swyftx"},
        # {"symbol": "WBTC-USD", "api": "swyftx"},
        {"symbol": "TRX-USD", "api": "swyftx"},
        {"symbol": "BAT-USD", "api": "swyftx"},
        # {"symbol": "AAVE-USD", "api": "swyftx"},
        {"symbol": "AVAX-USD", "api": "swyftx"},
        # {"symbol": "BCH-USD", "api": "swyftx"},
        {"symbol": "LINK-USD", "api": "swyftx"},
        {"symbol": "DAI-USD", "api": "swyftx"},
        #{"symbol": "GRT-USD", "api": "swyftx"},
        # {"symbol": "LTC-USD", "api": "swyftx"},
        # {"symbol": "MKR-USD", "api": "swyftx"},
        {"symbol": "SUSHI-USD", "api": "swyftx"},
        {"symbol": "YFI-USD", "api": "swyftx"},
    ],
}
input_symbols["everything"] = (
    input_symbols["crypto_symbols_all"] + input_symbols["nyse_symbols_big"]
)
