

class Strategy:
    def __init__(self):
        ...

    def add_symbol(self, symbol):...
    def remove_symbol(self, symbol):...
    def get_state(self, symbol):...
    def get_state_all(self):...
    def start_all(self):...
    def stop_all(self):...
    def start_one(self, symbol):...
    def stop_one(self, symbol):...

    